version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  tools:
    image: yourregistry/security-tools:latest
    container_name: security-tools
    volumes:
      - shared-data:/home/tools/shared
    networks:
      - app-network
    restart: always

  api:
    image: yourregistry/osint-api:latest
    environment:
      - TOOLS_CONTAINER_NAME=security-tools
    volumes:
      - shared-data:/home/app/shared
    depends_on:
      - db
      - tools
    networks:
      - app-network
    restart: always

  frontend:
    image: yourregistry/osint-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - app-network
    restart: always

volumes:
  pgdata:
  shared-data:

networks:
  app-network:
